Feat/YB-41 social login
YAPP-Github/YeoBee-BE pull request #3
Opened 2023-12-27 10:08 UTC by Y-Joo

## PR 요약

카카오, 애플 소셜 로그인을 구현했습니다.
#### 📌 변경 사항

- application.yml을 분리했습니다.
- Security를 사용하는 방식으로 구현했다가 ArgumentResolver을 사용하는 방식으로 변경했습니다.
  - 모든 요청이 아닌, AuthUser 어노테이션을 사용하는 api에 대해 토큰 검증이 작동합니다.
- 카카오, 애플 소셜 로그인을 구현했습니다
  -  iOS 측 로그인 호출 구현이 되면 테스트해볼 예정입니다.
  -  회원탈퇴는 유저를 완전히 삭제할지, deleted 칼럼을 두고 완전히 삭제하지는 않는지에 대한 정책이 정해지면 구현할 예정입니다.
##### ✅ PR check list

- ApiDocumentResponse 어노테이션은 AuthUser 어노테이션을 사용하는 모든 api에 대한 공통적인 에러를 swagger에서 사용하려 구현했는데, 혹시 더 좋은 방법이 있을까요?
- AuthUser 어노테이션을 사용하지 않는 api에 대한 토큰검증이 이루어지지 않는데, 이 부분에서 문제가 발생할 여지가 있을까요?
- application-local.yml, env는 개인적으로 공유드리겠습니다.
#### 이슈 번호

[YB-41]

2023-12-28 10:08 UTC, Gongmeda requested changes

2023-12-28 10:08 UTC, Gongmeda commented on src/main/java/com/example/yeobee/auth/apple/controller/AppleAuthController.java
> +    @ResponseBody
`@ResponseBody` 를 붙이신 이유가 뭔가요?

2023-12-28 10:08 UTC, Gongmeda commented on src/main/java/com/example/yeobee/auth/apple/dto/request/AppleLoginRequestDto.java
> +public record AppleLoginRequestDto(String code, String id_token) {
파라미터명에 underscore을 사용하신 이유가 뭔가요?

2023-12-28 12:03 UTC, Y-Joo commented on src/main/resources/application.yml
> +---
사용할 application.yml 프로필을 명시해주는 역할입니다!

2023-12-28 12:05 UTC, Y-Joo commented on src/main/java/com/example/yeobee/auth/apple/controller/AppleAuthController.java
> +public class AppleAuthController {
처음부터 버전을 붙이고 시작하면 클래스명이 길어서 보기 불편할 것 같은데,
버전업하는 시점에 V2컨트롤러를 만드는건 어떨까요?

2023-12-28 12:08 UTC, Y-Joo commented on src/main/java/com/example/yeobee/auth/apple/controller/AppleAuthController.java
> +    @ResponseBody
앗.. 코드를 가져오다보니 불필요한 코드가 있었네요 수정하겠습니다

2023-12-28 12:09 UTC, Y-Joo commented on src/main/java/com/example/yeobee/auth/apple/dto/request/AppleLoginRequestDto.java
> +public record AppleLoginRequestDto(String code, String id_token) {
애플 문서 참고하다가 그대로 써버렸네요 수정했슴다

2023-12-30 06:40 UTC, Y-Joo commented
@Gongmeda 코드 리팩토링 후 로직 작동 확인했고, 로그아웃 api 추가했습니다!

2024-01-03 12:07 UTC, Gongmeda approved these changes

2024-01-03 13:32 UTC, merged