Feat/YB-92 유저 api 작성
YAPP-Github/YeoBee-BE pull request #6
Opened 2024-01-12 02:33 UTC by Y-Joo

## PR 요약

유저 api를 구현했습니다

#### 📌 변경 사항

- 유저 api를 구현했습니다.
  - 모든 api는 연결된 oauth 계정이 하나라는 가정 하에 구현했습니다.
  - 조회
    - 본인 정보 조회 api입니다.
  - 수정
    - 닉네임 및 프로필 이미지 수정 api입니다.
    - 프로필 이미지를 null로 변경할 수 있기에, null에 대한 처리는 따로 하지 않았습니다. 
  - 삭제
    - 유저와 연관된 auth provider를 삭제한 후, user는 soft delete처리하도록 구현했습니다.
    - soft delete를 위한 isDeleted 칼럼을 추가했습니다.
- BaseEntity에 CreateDate 어노테이션은 LocalDateTime밖에 지원하지 않아, PrePersist를 사용하는 방식으로 변경했습니다.
- 테스트 컨테이너 데이터베이스 이름을 수정했습니다.
- 회원탈퇴 구현을 위해 카카오 adminKey 환경변수가 추가됐습니다. 프론트측에서 전달받으면 추가하면 됩니다.
- 프로필 이미지 칼럼 이름 변경(profileImage -> profileImegeUrl), isDeleted 칼럼 추가로 db migration V3 파일 추가했습니다.

##### ✅ PR check list

#### 이슈 번호

[YB-92]

2024-01-14 11:12 UTC, Gongmeda requested changes

2024-01-14 11:12 UTC, Gongmeda commented on src/main/java/com/example/yeobee/core/user/domain/User.java
> +    private boolean isDeleted = Boolean.FALSE;
그냥 `false`가 아니라 `Boolean.FALSE`를 사용하신 이유가 있나요?

2024-01-14 14:06 UTC, Y-Joo commented on src/main/java/com/example/yeobee/core/user/domain/User.java
> +    private boolean isDeleted = Boolean.FALSE;
처음에 Boolean으로 선언했다가 안바꿨네요,, 수정했습니다!

2024-01-14 14:08 UTC, Y-Joo commented
@Gongmeda 코드리뷰 반영했는데, AuthService를 이미 AppleAuthService랑 KakaoAuthService에서 참조하고 있는 상황이라, 양방향 참조가 일어나는 것을 막으려고 소셜 로그인별 분기처리를 컨트롤러 단으로 올렸습니다! 괜찮은지 확인 한번만 부탁드릴게요

2024-01-14 14:35 UTC, Gongmeda commented
> @Gongmeda 코드리뷰 반영했는데, AuthService를 이미 AppleAuthService랑 KakaoAuthService에서 참조하고 있는 상황이라, 양방향 참조가 일어나는 것을 막으려고 소셜 로그인별 분기처리를 컨트롤러 단으로 올렸습니다! 괜찮은지 확인 한번만 부탁드릴게요

이렇게 처리하면 안될꺼같아요. 일단 컨트롤러단에 비즈니스 로직이 들어가는것부터 이상하고, 트랜잭션 범위도 벗어나게 구현하셨는데 이걸 컨트롤러에 선언한다 하더라도 애초에 컨트롤러에 트랜잭션을 선언하는게 책임을 벗어난다고 생각합니다. 근본적으로 순환의존성을 없애는 구조로 바꿔야 할 것 같아요.

2024-01-14 14:52 UTC, Y-Joo commented
> > @Gongmeda 코드리뷰 반영했는데, AuthService를 이미 AppleAuthService랑 KakaoAuthService에서 참조하고 있는 상황이라, 양방향 참조가 일어나는 것을 막으려고 소셜 로그인별 분기처리를 컨트롤러 단으로 올렸습니다! 괜찮은지 확인 한번만 부탁드릴게요
> 
> 이렇게 처리하면 안될꺼같아요. 일단 컨트롤러단에 비즈니스 로직이 들어가는것부터 이상하고, 트랜잭션 범위도 벗어나게 구현하셨는데 이걸 컨트롤러에 선언한다 하더라도 애초에 컨트롤러에 트랜잭션을 선언하는게 책임을 벗어난다고 생각합니다. 근본적으로 순환의존성을 없애는 구조로 바꿔야 할 것 같아요.

그러네요..
AuthService가 Apple, KakaoAuthService 상위에서 내려주는 형태가 맞을 것 같아서, 이 구조로 통일시켜보겠습니다.

2024-01-15 10:33 UTC, Gongmeda requested changes

2024-01-15 10:33 UTC, Gongmeda commented on src/main/java/com/example/yeobee/core/auth/application/AuthService.java
> +        AuthProvider authProvider = getOrCreateAuthProvider(socialLoginId, AuthProviderType.KAKAO);
<img width="1010" alt="스크린샷 2024-01-15 오후 7 23 48" src="https://github.com/YAPP-Github/YeoBee-BE/assets/25472942/f3f0059d-722f-4a1f-ac20-f22e8adba38f">

`@Transactional` 어노테이션은 내부적으로 프록시 패턴을 사용하기 때문에 동일한 클래스 내에서 해당 어노테이션이 달려있는 메소드를 호출해도 동작하지 않습니다. `getOrCreateAuthProvider`를 호출하는 service의 최상위 메소드에 `@Transactional`을 달거나, 내부적으로 세부적인 트랜잭션 조정이 필요하면 둘 다 다는 방법이 있습니다.

2024-01-15 10:33 UTC, Gongmeda commented on src/main/java/com/example/yeobee/core/auth/application/AuthService.java
> +    public AuthProvider getOrCreateAuthProvider(String socialLoginId, AuthProviderType authProviderType) {
내부에서만 호출하는 메소드인데 접근제한자가 public인 이유가 있나요?

2024-01-15 10:33 UTC, Gongmeda commented on src/main/java/com/example/yeobee/core/auth/application/AuthService.java
> +    public AuthProvider getOrCreateAuthProvider(String socialLoginId, AuthProviderType authProviderType) {
동일한 클래스 내의 `issueToken` 메소드도 마찬가지 입니다

2024-01-15 10:33 UTC, Gongmeda commented on src/main/java/com/example/yeobee/core/auth/application/AppleAuthService.java
> +    private final RestTemplate restTemplate = new RestTemplateBuilder().build();
RestTemplate을 `RestTemplateConfig`에서 bean으로 선언해서 재사용하도록 설정이 되어있는데 따로 객체를 생성해서 사용하게 수정하신 이유가 뭔가요?

2024-01-15 10:33 UTC, Gongmeda commented on src/main/java/com/example/yeobee/core/auth/application/KakaoAuthService.java
> +    private final RestTemplate restTemplate = new RestTemplateBuilder().build();
AppleAuthService에서 언급한 내용과 마찬가지 입니다

2024-01-15 11:09 UTC, Y-Joo commented on src/main/java/com/example/yeobee/core/auth/application/AppleAuthService.java
> +    private final RestTemplate restTemplate = new RestTemplateBuilder().build();
로그인 에러 수정중에 이것저것 시도해보다가 객체 생성이 제대로 안됐나 해서
생성해서 사용하는 방식으로 바꿔봤는데 작동하길래 객체 생성이 제대로 안되서 그런 줄 알았는데,
RestTemplateConfig가 있던걸 까먹고 있었네요.
재사용하는 방식으로 다시 테스트해보겠습니다.

2024-01-15 15:22 UTC, Gongmeda approved these changes
수고하셨습니다! 😄

2024-01-15 15:24 UTC, merged